from enum import Enum


class ResourceId(Enum):
    """ Data's Resource ID using Enum """
    AREA_RESOURCE_ID = 1
    QUARANTINE_RESOURCE_ID = 2
    LAB_TESTS_RESOURCE_ID = 3
    TESTED_INDIVIDUALS_RESOURCE_ID = 4
    TESTED_INDIVIDUALS_SCORES_RESOURCE_ID = 5
    RECOVERED_RESOURCE_ID = 6
    HOSPITALIZED_DATA_RESOURCE_ID = 7
    AGE_GENDER_DATA_RESOURCE_ID = 8
    MEDICAL_STAFF_MORBIDITY_RESOURCE_ID = 9
    DEATHS_DATA_RESOURCE_ID = 10
    YOUNG_POPULATION_RESOURCE_ID = 11
    CITIES_POPULATION_RESOURCE_ID = 12
